lang: ru-RU
encoding: utf-8

title: "Медвежий угол"
description: "Стихи, рассказы и путевые заметки Марка Шевченко."

author: "Марк Шевченко"
url: http://mark.shevchenko.name

permalink: pretty
highlighter: rouge

paginate: 10
paginate_path: "/posts/:num"

exclude:
  - Gemfile
  - CNAME
  - LICENSE
  - README.md

markdown: kramdown

kramdown:
  auto_ids: true

gems:
  - jekyll-paginate
